setInterval(function() { document.getElementById('clickable-hitwall').click(); }, 10);							
setInterval(function() { document.getElementById('building-puncher').click(); }, 500);							
setInterval(function() { document.getElementById('building-clubber').click(); }, 500);		
setInterval(function() { document.getElementById('building-swordsman').click(); }, 500);		
setInterval(function() { document.getElementById('building-gunner').click(); }, 500);		
setInterval(function() { document.getElementById('building-grenade').click(); }, 500);		
setInterval(function() { document.getElementById('building-wreckingball').click(); }, 500);		
setInterval(function() { document.getElementById('building-bulldozer').click(); }, 500);		
setInterval(function() { document.getElementById('building-airstrike').click(); }, 500);		
